# Generated by Django 4.1.2 on 2022-11-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tablaproducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('tipoproducto', models.CharField(max_length=100)),
                ('marcaproducto', models.CharField(max_length=100)),
                ('descripcionproducto', models.TextField(max_length=100)),
                ('stockproducto', models.IntegerField()),
                ('precioproducto', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='tablausuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
