# Generated by Django 4.1.2 on 2022-11-06 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mipalo', '0002_tablacompra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablausuario',
            old_name='password',
            new_name='contra',
        ),
    ]
