# Generated by Django 4.1.2 on 2022-11-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipalo', '0003_rename_password_tablausuario_contra'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablacompra',
            name='imagencompra',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.AddField(
            model_name='tablaproducto',
            name='imagenproducto',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
