# Generated by Django 4.1.2 on 2022-11-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mipalo', '0004_tablacompra_imagencompra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablacompra',
            name='imagencompra',
        ),
        migrations.RemoveField(
            model_name='tablaproducto',
            name='imagenproducto',
        ),
    ]
