# Generated by Django 4.1.2 on 2022-11-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipalo', '0005_remove_tablacompra_imagencompra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablacompra',
            name='compraimagen',
            field=models.ImageField(null=True, upload_to='compras'),
        ),
        migrations.AddField(
            model_name='tablaproducto',
            name='productoimagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
